### ISSUE TITLE
test failures with ruby2.5

### ISSUE THREAD

**Issue by boutil** [thumblemonks/riot#55]
Hi,

As mentionned in https://github.com/thumblemonks/riot/pull/54, some tests are failing with ruby 2.5.
```
An AssertionMacro instance receiving #new_message
  - asserts to_s: expected "\"hope\"", not "hope" send :to_s
An AssertionMacro instance receiving #should_have_message
  - asserts to_s: expected "should have \"hope\"", not should have "hope" send :to_s
An AssertionMacro instance receiving #expected_message
  - asserts to_s: expected "expected \"hope\"", not expected "hope" send :to_s
A kind_of assertion macro :fail when not a kind of String
- asserts failure message: expected "expected kind of String, not Fixnum", not "expected kind of String, not Integer"
```
The last one is caused to the transition from Fixnum to Integer, but in the three other it seems that the AssertionMacro is recording the call to to_s as a message with ruby2.5. When trying to reproduce in irb, I fail. Can you confirm that the library is working correctly, but the problem is caused by the test itself?

The bug is reported in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888171

Cheers,
Cédric

**Comment by gus** [comment]
Hey @boutil, thanks for bringing this up again. Going to take a look today.

I also might transfer this repo to my [HeavySet](https://github.com/heavyset) organization, which is a company I own with two partners. Just letting you know in case you see some unexpected changes :)

**Comment by gus** [comment]
Hey @boutil - turns out the tests were broken, but not the source code itself. Changes in ruby 2.4 caused problems in the way certain tests were set up. So, fixed the tests and all is well now. Thanks for pinging.

For the record, no new release is going out. But, I am interested in whether there are changes you would like in general to Riot. I joined a startup about 8 years ago and only left as of last December (2017). Didn't really get a chance to work on Ruby stuff while I was there, so didn't devote a lot of energy to Riot. Anyway, if you have any thoughts, please post a feature request.

Cheers,
Gus

**Comment by boutil** [comment]
Thanks a lot!
Actually, I am not using this project directly. But I am maintaining some Ruby packages for the Debian GNU/Linux distribution and riot comes as the build dependency of another package (rabl).
But if it turns out we need some features, I know where to ask!

Cheers,

Cédric
